apiVersion: v1
kind: Service
metadata:
  labels:
    app: uda-users
  name: uda-users-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: uda-users